export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST'
export const PASSWORD_RESET_REQUEST_SUCCESS = 'PASSWORD_RESET_REQUEST_SUCCESS'
export const PASSWORD_RESET_REQUEST_ERROR = 'PASSWORD_RESET_REQUEST_ERROR'

export const PASSWORD_RESET_CONFIRM_REQUEST = 'PASSWORD_RESET_CONFIRM_REQUEST'
export const PASSWORD_RESET_CONFIRM_REQUEST_SUCCESS =
  'PASSWORD_RESET_CONFIRM_REQUEST_SUCCESS'
export const PASSWORD_RESET_CONFIRM_REQUEST_ERROR =
  'PASSWORD_RESET_CONFIRM_REQUEST_ERROR'