export const POST_REQUEST = 'POST_REQUEST'
export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS'
export const POST_REQUEST_ERROR = 'POST_REQUEST_ERROR'
export const POST_CLEAR = 'POST_CLEAR'

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_REQUEST_SUCCESS = 'POST_LIST_REQUEST_SUCCESS'
export const POST_LIST_REQUEST_ERROR = 'POST_LIST_REQUEST_ERROR'

export const POST_LIST_OPTIONS_REQUEST = 'POST_LIST_OPTIONS_REQUEST'
export const POST_LIST_OPTIONS_REQUEST_SUCCESS =
  'POST_LIST_OPTIONS_REQUEST_SUCCESS'
export const POST_LIST_OPTIONS_REQUEST_ERROR = 'POST_LIST_OPTIONS_REQUEST_ERROR'